module.exports = {
	name: 'help',
	description: 'Help Embed',
	execute(message, args) {

const { ver } = require('../config.json');
const Discord = require('discord.js');
const title = new Discord.MessageEmbed()
	.setColor('#fefefe')
	.setImage('')
	.setTitle('**MAJIKTRIKBOT HELP**')
	.setAuthor('MajikTrikBot' + ver, 'https://cdn.discordapp.com/avatars/646441583176056842/3a225a4d8ea65147d1e7090555ba772d.png?size=256')
	.setDescription(`Our commands are listed below. If you would like to contact us, get the latest updates, report an error or bug, or just want to join our community, do so below or right here => [Join](https://discord.gg/Vqra7ZQ 'Majiktrikbot Official')`)
	.addField('\u200b', '\u200b')
	.addField(`Latest Update`, ver, true)
	.addField(`Join Our Community!`, `[Join](https://discord.gg/Vqra7ZQ 'Majiktrikbot Official')`, true)
	.addField(`Check out our Website!`, `[Website](https://sites.google.com/view/majiktrikbot 'Majiktrikbot Website(WIP)')`, true)
	.setTimestamp()
	.setFooter('Help Page 1 of 1', 'https://cdn.discordapp.com/avatars/646441583176056842/3a225a4d8ea65147d1e7090555ba772d.png?size=256')
const S_general = new Discord.MessageEmbed()
.setColor('#a3a3a3')
.setTitle('General / Information')
.setDescription(`Boooooooooooooooooring.`)
.addField('>help', 'This Very Screen', true)
.addField('>clear', 'Clears. add -s for silence', true)
.addField('>ping', 'Pong!', true)
.addField('>beep', 'Boop!', true)
.addField('>args-info', 'test cmd', true)
.addField('>mail', 'Wheeeeeeeeeeeeeeee', true)
.addField('>announce', 'HEY YOU!', true)
.addField('>ver', 'Version and Changelog', true)
.addField('>vote', 'Starts a Poll', true)
.addField('>login', 'Dev Debug Command', true)
.addField('>me', 'Gives Detailed Information about yourself', true)
.addField('>who', 'Gives Detaied Inforamation about another user', true)
.addField(`>info`, `Gives Detailed Server Information`, true)
const S_Money = new Discord.MessageEmbed()
.setColor('#00FF00')
.setTitle('Economy / Money')
.setDescription(`Money Printer go brrrrr`)
.addField(`>Money`, `Shows ya Money`, true)
.addField(`>work`, `Get a Job!`, true)
.addField(`>Pay`, `Coming Soon`, true)
.addField(`>deposit`, `Put it in the bank`, true)
.addField(`>withdraw`, `Take it out of the bank`, true)
const S_Games = new Discord.MessageEmbed()
.setColor('#0000FF')
.setTitle('Fun / Games')
.setDescription(`WHIPEE!`)
.addField('>games', 'Shows list of games', true)
.addField('>claim', 'Mine Now', true)
.addField('>flip', 'Flip it!', true)
.addField('>8ball', 'THE HOLY MAJIKAL 8 BALL', true)
.addField('>majiktrik', 'Shows You a Majik Trik', true)
const S_Punishment = new Discord.MessageEmbed()
.setColor('#FF0000')
.setTitle('Punishment')
.setDescription('We dont really do that....')
.addField('>ban', 'You know what this does', true)
  message.channel.send(title)
  message.channel.send(S_general)
  message.channel.send(S_Games)
  message.channel.send(S_Money)
  message.channel.send(S_Punishment)
	},
}